/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logistica.h"

int *
pedir_gasolina_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

char **
pedir_desafio_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
autenticar_1(argp, rqstp)
	char **argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
pedir_tiempo_1(argp, rqstp)
	void *argp;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
