/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGISTICA_H_RPCGEN
#define _LOGISTICA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define LOGISTICA 600910285
#define LOGISTICA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define pedir_gasolina 1
extern  int * pedir_gasolina_1(char **, CLIENT *);
extern  int * pedir_gasolina_1_svc(char **, struct svc_req *);
#define pedir_desafio 2
extern  char ** pedir_desafio_1(char **, CLIENT *);
extern  char ** pedir_desafio_1_svc(char **, struct svc_req *);
#define autenticar 3
extern  int * autenticar_1(char **, CLIENT *);
extern  int * autenticar_1_svc(char **, struct svc_req *);
#define pedir_tiempo 4
extern  int * pedir_tiempo_1(void *, CLIENT *);
extern  int * pedir_tiempo_1_svc(void *, struct svc_req *);
extern int logistica_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define pedir_gasolina 1
extern  int * pedir_gasolina_1();
extern  int * pedir_gasolina_1_svc();
#define pedir_desafio 2
extern  char ** pedir_desafio_1();
extern  char ** pedir_desafio_1_svc();
#define autenticar 3
extern  int * autenticar_1();
extern  int * autenticar_1_svc();
#define pedir_tiempo 4
extern  int * pedir_tiempo_1();
extern  int * pedir_tiempo_1_svc();
extern int logistica_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGISTICA_H_RPCGEN */
